### ISSUE TITLE
Verify if the url is valid before passing to the browser driver

### ISSUE THREAD

**Issue by heynemann** [heynemann/pyccuracy#1]
A lot of users are getting a cryptic error from Selenium when they forget to pass the -u setting, because they are sending to selenium server an invalid url.

We need to do some url verify and give the user a meaningful error.

**Comment by gabrielfalcao** [comment]
Added a URLChecker to the go to action. Closed by a2547cf6b01f5f4bc865e4ce87b567409251d253
