### ISSUE TITLE
Improve error message when no scenario line found

### ISSUE THREAD

**Issue by jcfigueiredo** [heynemann/pyccuracy#12]
File "/home/claudio/usr/lib/python/pyccuracy/test_fixture_parser.py", line 92, in __process_lines
    raise RuntimeError(self.language["no_scenario_line_error"] % line)
RuntimeError: Não havia uma linha "Cenário X - Descrição" antes da ação: #TODO: REMOVER TODOS OS 'Eu espero por x segundos'

**Comment by heynemann** [comment]
Already implemented in release 0.6.*
