### ISSUE TITLE
New approach for Actions

### ISSUE THREAD

**Issue by gabrielfalcao** [heynemann/pyccuracy#17]
Nowadays to write a custom action you need to write a very copy-and-paste-ish code:

 class DoSomeAction(ActionBase):
     def matches(self, line):

```
     reg = r'I do (?P<what>\w+) something on the page'
     self.last_match = reg.search(line)

     return self.last_match



 def values_for(self, line):

     return self.last_match and (self.last_match.groups()[1],) or tuple([])



 def execute(self, values, context):

     what_to_do = values[0]
     ...
     rest of code
     ...
```

Pyccuracy should implement something more declarative, I.e:

 class DoSomeAction(ActionBase):
     regex = r'I do (?P<what>\w+) something on the page'

```
 def execute(self, context, *args, **kwargs):
     what_to_do = kwargs['what']
     ...
     rest of code
     ...
```

In the new approach, the method execute will take both regex groups and named groups in args and kwargs.

**Comment by heynemann** [comment]
Already implemented in 0.6.*.
