### ISSUE TITLE
Adjust the scenario/seconds rate message to a more meaningfull one

### ISSUE THREAD

**Issue by jcfigueiredo** [heynemann/pyccuracy#23]
# 
# Sumário dos Testes

1 stories tiveram sucesso (100.00%)
0 stories falharam (0.00%)
1 cenários tiveram sucesso (100.00%)
0 cenários falharam (0.00%)

Resultado dos Testes: SUCCESSFUL
1 Cenários executados em 34.73 s
Taxa de execução de cenários: 0.03 cenários/segundo

**Comment by heynemann** [comment]
DEFERRED. The current message is as good as it can be.
