### ISSUE TITLE
[Windows] - Lack of lxml library mentions only aptitude instructions

### ISSUE THREAD

**Issue by knorrium** [heynemann/pyccuracy#40]
When running Pyccuracy without lxml installed on Windows, the following message is displayed

"Sorry, but you need to install lxml (python-lxml in aptitude) before using the report feature in pyccuracy."

Instructions for Windows could also be displayed. 

"easy_install lxml" works :)

**Comment by heynemann** [comment]
Cool. Great idea... Will be done.

**Comment by heynemann** [comment]
This issue doesn't apply anymore since a whole install guide can be found in www.pyccuracy.org
