### ISSUE TITLE
Pyccuracy won't work with confirm dialogs and alert dialogs.

### ISSUE THREAD

**Issue by cabello** [heynemann/pyccuracy#43]
I noticed that when you click on something that raises a confirm or alert box, you need to consume that with selenium, so I implemented this stuff in Pyccuracy, you can find the diff and the example files in the links above:

Diff from the repository to after my work
http://paste.pocoo.org/show/130223/ (gone =/)

Alert html and acc
http://paste.pocoo.org/show/130224/ (gone =/)

Confirm html and acc
http://paste.pocoo.org/show/130225/ (gone =/)

Keep the good job guys, I plan to use Pyccuracy a lot, and I hope to be able to always help the project.

**Comment by marcossousa** [comment]
Hello, 

I did the implementation for confirm window. The implementation is waiting for approval. By the way the DSL is pretty similar as proposed above. 

I'll implement the alert too.

**Comment by cabello** [comment]
This is probably fixed by now.
