### ISSUE TITLE
dependency to lxml missing

### ISSUE THREAD

**Issue by japj** [heynemann/pyccuracy#49]
Given lxml is not installed
When I run "easy_install pyccuracy"
Then lxml should automaticly be installed before installing pyccuracy

Actual result during easy_install:
ImportError: No module named lxml

note: the same goes for selenium

**Comment by heynemann** [comment]
I'm not sure either of them have setuptools packages, but if they do I'll add them asap.

Thanks!

**Comment by heynemann** [comment]
LXML is not actually required. Selenium is. The issue that showed that message is fixed in 1.2.26.
