### ISSUE TITLE
Problem with new version 1.2.27

### ISSUE THREAD

**Issue by aoqfonseca** [heynemann/pyccuracy#56]
When i try execute my acceptance test,  the pyccuracy console said : 

pkg_resources.VersionConflict: (Pyccuracy 1.2.27 (/....), Requirement.parse('Pyccuracy==1.2.25'))

Is there anything to do before this install? Is normal ?

**Comment by heynemann** [comment]
This was an issue caused by setuptools.
It overrode the pyccuracy_console code with some code from setuptools, rendering the console useless.
