### ISSUE TITLE
easy_install - instalation error

### ISSUE THREAD

**Issue by those** [heynemann/pyccuracy#62]
error in pyccuracy installation using easy_install:

those@rtfm:~$ sudo easy_install pyccuracy
Searching for pyccuracy
Reading http://pypi.python.org/simple/pyccuracy/
Download error: [Errno 101] Network is unreachable -- Some packages may not be found!
Reading http://pypi.python.org/simple/pyccuracy/
Download error: [Errno 101] Network is unreachable -- Some packages may not be found!
Couldn't find index page for 'pyccuracy' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading http://pypi.python.org/simple/
Download error: [Errno 101] Network is unreachable -- Some packages may not be found!
No local packages or download links found for pyccuracy
error: Could not find suitable distribution for Requirement.parse('pyccuracy')

**Comment by heynemann** [comment]
Looks like you had some connectivity errors: [Errno 101] Network is unreachable

Can you confirm that it's still an issue?

**Comment by guilhermechapiewski** [comment]
I edited my /etc/hosts file to map "pypi.python.org" to a random IP, which caused a similar conectivity error.

Probably there was some problem with PyPI when you tested or even there was something wrong with your network connection.

This is definitely not an issue with Pyccuracy, therefore I'm closing the ticket.
