### ISSUE TITLE
Be possible to select an element by its xpath

### ISSUE THREAD

**Issue by igorsantos07** [heynemann/pyccuracy#67]
I found it's impossible to, in example, click a link that doesn't have a name or an ID.
I couldn't use XPath to select it too, and I think it would be a nice feature to be implemented.

**Comment by heynemann** [comment]
Have you checked the page register API?

**Comment by igorsantos07** [comment]
Yes... but in our project it's quite common to have links with no name or ID, but classes.
I found it would be rather consuming to create Pages to access those common links.
A quick example is the site's menu, present in all pages. I would need to register all the links for all pages we test?
