### ISSUE TITLE
Tag not active on the issues filter tab, yet filter is active

### ISSUE THREAD

**Issue by brunoise** [heynemann/pyccuracy#81]
https://github.com/UCL/rcps-general/issues?labels=Project%3A+new+stack&milestone=&page=1&state=open

This bug is encapsulated in the URL above - the Project: New Stack filter appears to be active, yet the tag filter tab does not indicate that this filter is selected.

If I select the Project: New Stack tag filter in the page encoded in this URL, it actually filters out all tickets, including the ones that have the Project: New Stack tag, which is another incorrect behaviour.

The only way to get out of this state is to click the remove all filters button.

I have seen many instances of this bug occur where I cannot see a significant number of all open issues and no filter is selected.

**Comment by jamespjh** [comment]
I think this is probably an escaping issue do to the colon in the label, but that's just a guess.

**Comment by jamespjh** [comment]
Sorry, bug raised in wrong project.
