### ISSUE TITLE
Issue tracker gets confused when commits have random # in them

### ISSUE THREAD

**Issue by felipec** [heynemann/pyccuracy#83]
I have my own clone of git.git where I track the development of git-remote-hg and git-remote-bzr, I have an issue tracker, wiki and so on.

However, at some points I merge from upstream git.git, and when somebody says #1, or #2, the issue tracker thinks somebody called him, and closes the bug even though t was not intended at all.

You can see that in https://github.com/felipec/git/issues/2, which is a complete mess of commits "referencing" this issue.

There should be an option to disable this.

**Comment by diogobaeder** [comment]
Let me guess, wrong project, right?!

How did you end up finding this project? Sorry to ask, it's just that lots of people are opening bugs to this project, thinking that it's GitHub, so I'd like to find out what's bringing them all to pyccuracy, and avoid this to happen again.

**Comment by felipec** [comment]
Sorry, I googled "github report bugs", it's the first result.

**Comment by diogobaeder** [comment]
Ahhh, there it is! https://github.com/heynemann/pyccuracy/wiki/Requesting-features,-reporting-bugs-and-contributing

Thanks man, that actually helped us! I'll change the title so that it's explicit that the page is about Pyccuracy, and not GitHub. :-)
