### ISSUE TITLE
What language does Pyccuracy implement?

### ISSUE THREAD

**Issue by webmaven** [heynemann/pyccuracy#86]
Is it a variant of [Gherkin](https://github.com/cucumber/cucumber/wiki/Gherkin), or something else?

**Comment by heynemann** [comment]
Not really... Pyccuracy has its own language. Actually I first implemented it in .NET, then later on in python.

**Comment by webmaven** [comment]
I see. It is going to be difficult to find a maintainer unless the Pyccuracy language has advantages over Gherkin, which seems like it is becoming a standard for BDD.

**Comment by heynemann** [comment]
Not sure whether it has advantages over Gherkin. It's more of  a different language.
